In [1]:
import nibabel as nib
import numpy as np

# Load ground truth & reconstruction
gt_img = nib.load("/projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/data/nnUNet_preprocessed/Dataset001_nnunet/gt_segmentations/case_026.nii.gz")
recon_img = nib.load("/projectnb/ec500kb/projects/Project_4/Graph_Creations/Everything_For_Docker/output2/pred_case_026_0000.nii.gz")

gt = gt_img.get_fdata().astype(int)
recon = recon_img.get_fdata().astype(int)

# Class names
classes = {
    0: "background",
    1: "artery",
    2: "vein",
    3: "unknown"
}

# Count voxels per class
counts_gt = {c: int(np.sum(gt == c)) for c in classes}
counts_recon = {c: int(np.sum(recon == c)) for c in classes}

print("=== Voxel Counts ===")
print("Ground Truth:", counts_gt)
print("Reconstruction:", counts_recon)

# Compute confusion matrix
cm = np.zeros((4,4), dtype=int)
for c in range(4):
    for r in range(4):
        cm[c, r] = np.sum((gt == c) & (recon == r))

print("\n=== Confusion Matrix (rows = GT, cols = Reconstruction) ===")
print("Rows:    0 BG, 1 Art, 2 Vein, 3 Unk")
print("Columns: 0 BG, 1 Art, 2 Vein, 3 Unk\n")
print(cm)

# Dice coefficient for artery & vein
def dice(a, b):
    intersection = np.sum((a==1) & (b==1))
    return 2*intersection / (np.sum(a==1) + np.sum(b==1) + 1e-8)

dice_artery = dice(gt==1, recon==1)
dice_vein   = dice(gt==2, recon==2)

print("\n=== Dice Scores ===")
print("Artery Dice:", dice_artery)
print("Vein Dice:  ", dice_vein)


=== Voxel Counts ===
Ground Truth: {0: 85589091, 1: 718476, 2: 724241, 3: 0}
Reconstruction: {0: 85482999, 1: 773870, 2: 774939, 3: 0}

=== Confusion Matrix (rows = GT, cols = Reconstruction) ===
Rows:    0 BG, 1 Art, 2 Vein, 3 Unk
Columns: 0 BG, 1 Art, 2 Vein, 3 Unk

[[85279230   145199   164662        0]
 [   78804   520046   119626        0]
 [  124965   108625   490651        0]
 [       0        0        0        0]]

=== Dice Scores ===
Artery Dice: 0.6969509751759934
Vein Dice:   0.6545591590069194
